# Site settings
title: Ben's Profile
email: byfyang@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Ben's Portfolio
baseurl: "patchwork-gh-pages"
url: "http://byfyang.github.io"

github_username:  byfyang



# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
